In [1]:
import numpy as np

In [4]:
# 1. Write a NumPy program to add a vector to each row of a given matrix.
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([0, 2, 4])
a+b

array([[ 1,  4,  7],
       [ 4,  7, 10],
       [ 7, 10, 13]])

In [19]:
# 2. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
np.fromfunction(lambda i,j: (i==j)*(i+1), (5, 5), dtype = np.int)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [32]:
# 3.  Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
np.fromfunction(lambda i,j: ((i==0)+(i==9)+(j==0)+(j==9))*1, (10, 10), dtype=np.int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [34]:
# 4. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
a = np.arange(10, 22, 1)
a = a.reshape((3,4))
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [40]:
# 5. Write a NumPy program to create a 3X4 array using and iterate over it.
for i in a:
    for j in i:
        print(j, end=" ")

10 11 12 13 14 15 16 17 18 19 20 21 

In [46]:
# 6. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.
a = np.array([[10, 14, 4], [2, 5, 21]])
print(a[a>=10])
print(np.where(a>=10))

[10 14 21]
(array([0, 0, 1], dtype=int64), array([0, 1, 2], dtype=int64))


In [48]:
# 7. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere. 
a = np.array([4, 5, 6, 8])
b = np.fromfunction(lambda i,j: (i==j)*a, (4, 4))
b

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [51]:
# 8. Write a NumPy program to to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.
np.logspace(2, 5, 20, endpoint=False)

array([  100.        ,   141.25375446,   199.5262315 ,   281.83829313,
         398.10717055,   562.34132519,   794.32823472,  1122.0184543 ,
        1584.89319246,  2238.72113857,  3162.27766017,  4466.83592151,
        6309.5734448 ,  8912.50938134, 12589.25411794, 17782.79410039,
       25118.8643151 , 35481.33892336, 50118.72336273, 70794.57843841])

In [53]:
# 9. Write a NumPy program to to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.
a = np.array([[0,1,3], [5,7,9]])
b = np.array([[0,2,4], [6,8,10]])
np.concatenate((a, b), axis=1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [115]:
# 10. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis.
a = np.arange(16).reshape((4, 4))
np.split(a, (2), axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [89]:
# 11. Write a NumPy program to find unique rows in a NumPy array.
x = np.array([[0,9,7], [0,9,7], [1,2,3],[4,3,6],[1,4,2],[1,2,3],[0,9,7]])
a = np.ones(len(x), dtype=bool)
for i in range(1, len(x)):
    for j in range (i):
        if (x[i]==x[j]).all(): a[j] = False
x[a]

array([[4, 3, 6],
       [1, 4, 2],
       [1, 2, 3],
       [0, 9, 7]])

In [71]:
# 12. Write a NumPy program to remove the negative values in a NumPy array with 0.
a = np.array([-3, 5, 2, -6, -1])
a[a<0] = 0
a

array([0, 5, 2, 0, 0])

In [72]:
# 13. Write a NumPy program to get the magnitude of a vector in NumPy.
a = np.array([1,2,3,4,5])
np.sqrt(np.sum(a**2))

7.416198487095663

In [102]:
# 14. Write a NumPy program to count the frequency of unique values in NumPy array. 
a = np.random.randint(1, 6, 10)
print(a)
print(np.unique(a, return_counts=True))

[3 4 3 4 2 4 3 2 5 3]
(array([2, 3, 4, 5]), array([2, 4, 3, 1], dtype=int64))


In [107]:
# 15. Write a NumPy program to divide each row by a vector element.
a = np.array([[20,20,20],[30,30,30],[40,40,40]])
b = np.array([[20,30,40]]).T
a/b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [109]:
# 16. Write a NumPy program to calculate the Euclidean distance.
a = np.array([1,2,3])
b = np.array([4,5,6])
np.sqrt(np.sum((a-b)**2))

5.196152422706632

In [122]:
# 17. Write a NumPy program to access last two columns of a multidimensional columns.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
_, b = np.split(a, (-2,), axis=1) # result = arra[:,[1,2]]
b

array([[2, 3],
       [5, 6],
       [8, 9]])

In [125]:
# 18. Write a NumPy program to count the occurrence of a specified item in a given NumPy array.
a = np.random.randint(1, 6, 10)
n = input("Enter item: ")
print(a, len(a[a==int(n)]))

Enter item: 3
[3 5 5 5 1 5 4 2 1 3] 2


In [128]:
# 19. Write a NumPy program to remove nan values from a given array.
a = np.array([1, 4, np.nan, np.nan, 0, 6, 2, np.nan])
a[1-np.isnan(a)]

array([4., 4., 1., 1., 4., 4., 4., 1.])

In [153]:
# 20. Write a NumPy program to create a Cartesian product of two arrays into single array of 2D points.
x = np.array([1,2,3])
y = np.array([4,5])
xx = np.array([])
yy = np.array([])
for i in range (len(y)):
    xx = np.concatenate((xx, x))
for j in range (len(x)):
    yy = np.concatenate((yy, y))
    yy = np.sort(yy)
np.concatenate((xx[:, np.newaxis], yy[:, np.newaxis]), axis=1)

array([[1., 4.],
       [2., 4.],
       [3., 4.],
       [1., 5.],
       [2., 5.],
       [3., 5.]])

# Task 2

In [164]:
a = np.genfromtxt('hw3_file.txt', dtype=None, names=True, encoding='utf-8')
a

array([(1, 6. , 8.5), (2, 3.1, 6.9), (3, 1.6, 7.2), (4, 3.5, 9.1),
       (5, 4.8, 2.3), (6, 2.1, 0.4)],
      dtype=[('int', '<i4'), ('c_real', '<f8'), ('c_img', '<f8')])

In [195]:
A = np.zeros(len(a), dtype=[('int', 'i4'), ('c_real', 'f8'), ('c_img', 'f8')])
for i in range (len(a)):
    x = a[i][1] + a[i][2]*(1j)
    A['c_real'][i] = np.real(np.exp(x))
    A['c_img'][i] = np.imag(np.exp(x))
A['int'] = np.array([1,2,3,4,5,6])

In [196]:
np.savetxt('hw3_result_file.txt', A, fmt = '%d %.8f %.8f')
np.genfromtxt('hw3_result_file.txt', dtype=None, encoding='utf_8')

array([(1, -242.86893557, 322.13269247), (2,   18.10742603,  12.84017771),
       (3,    3.01318379,   3.93106266), (4,  -31.38422919,  10.56708649),
       (5,  -80.95947753,  90.61095168), (6,    7.52154058,   3.18005635)],
      dtype=[('f0', '<i4'), ('f1', '<f8'), ('f2', '<f8')])