# Numpy 8 (File i/o)

In [1]:
import numpy as np

In [2]:
Amat = np.loadtxt('3by3.txt')
X, Y, Z = np.loadtxt('3by3.txt', usecols=(0,1,2), unpack=True)
print(Amat)
print(X, Y, Z)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[1. 4. 7.] [2. 5. 8.] [3. 6. 9.]


In [3]:
Bmat = np.loadtxt('3bt3comma.txt', delimiter=",", skiprows=2)
Bmat

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [4]:
A = np.genfromtxt('a.txt', dtype=('S1', float, int)) #S1:string 1-byte
B = np.genfromtxt('a.txt', dtype=None, encoding='utf-8')
C = np.genfromtxt('a.txt', dtype=None, names=True, encoding='utf-8')
A, B, C

(array([(b'A', 1.1, 10), (b'B', 1.2, 20), (b'C', 1.3, 30)],
       dtype=[('f0', 'S1'), ('f1', '<f8'), ('f2', '<i4')]),
 array([('A', 1.1, 10), ('B', 1.2, 20), ('C', 1.3, 30)],
       dtype=[('f0', '<U1'), ('f1', '<f8'), ('f2', '<i4')]),
 array([('A', 1.1, 10), ('B', 1.2, 20), ('C', 1.3, 30)],
       dtype=[('name', '<U1'), ('v1', '<f8'), ('v2', '<i4')]))

In [5]:
X = np.array([1,2,3])
Y = np.array([4,5,6])
A = np.c_[X,Y] # column stack: np.colum_stack((X,Y))
np.savetxt('XY.txt', A, fmt = '%20.10f')
np.savetxt('XYstring.txt', A, fmt = '%s')

In [6]:
A = np.zeros(3, dtype=[('f0', 'U1'), ('f1', 'f8'), ('f2', 'i8')])
A['f0'] = np.array(['A', 'B', 'C'])
A['f1'] = np.array([1.1, 1.2, 1.3])
A['f2'] = np.array([10, 20, 30])

np.savetxt('Atest.txt', A, fmt="%-10s%-10.1f%10d")
np.genfromtxt('Atest.txt', dtype=None, encoding='utf-8')

array([('A', 1.1, 10), ('B', 1.2, 20), ('C', 1.3, 30)],
      dtype=[('f0', '<U1'), ('f1', '<f8'), ('f2', '<i4')])

In [7]:
A

array([('A', 1.1, 10), ('B', 1.2, 20), ('C', 1.3, 30)],
      dtype=[('f0', '<U1'), ('f1', '<f8'), ('f2', '<i8')])