# Numpy 1 (array)

In [1]:
import numpy as np

In [4]:
# row-major order
a = np.array([[0,1,2,3], [4,5,6,7]]) # default: float
print(a)

a = np.arange(0, 2, 0.5) # default: step=1
print(a)
a = np.linspace(0, 2, 4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]
[0.  0.5 1.  1.5]
[0.         0.66666667 1.33333333 2.        ]


In [5]:
a = np.array([0,1,2,3])
print(a.ndim, a.shape, len(a))
a = np.array([[0,1,2,3],[4,5,6,7]])
print(a.ndim, a.shape, len(a))

1 (4,) 4
2 (2, 4) 2


# Numpy 2 (dtype)

In [8]:
b = np.array([1,2])
print(b.dtype)
b = np.array([1.,2.])
print(b.dtype)
b = np.array([1,2], dtype=np.float64) # int32, int64, float64, complex128
print(b.dtype)

int32
float64
float64


In [9]:
a = np.int8(127)
b = np.int8(1)
c = np.int8(2)

print(a+b, a+c)

-128 -127


C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in byte_scalars
  """


In [10]:
print(1.0 + 2.0**-52)
print(1.0 + 2.0**-53)

1.0000000000000002
1.0


In [12]:
# float32: 6 / float64: 15
a = np.float32(1.0)
b = np.float32(1.0e-8)
for i in range (100000000): a = a + b
print(a)

a = np.float64(1.0)
b = np.float64(1.0e-8)
for i in range (100000000): a = a + b
print(a)

1.0
1.999999993922529


# Numpy 3 (array creation)

In [27]:
a = np.ones((2,3))
print(a)
a = np.ones((2,3), dtype=int)
b = np.zeros_like(a)
print(a)
print(b)

s = (2,3)
print(np.ones(s))

x = np.arange(6)
x = x.reshape((2,3)) # it does have to match the size
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 1 2]
 [3 4 5]]


In [29]:
print(np.fromfunction(lambda a,b: (a+1)*b, (3,4)))

[[0. 1. 2. 3.]
 [0. 2. 4. 6.]
 [0. 3. 6. 9.]]


In [34]:
def func1(a,b):
    print("inside:", a,b)
    return (a+1)*b # array
print("array:", np.fromfunction(func1, (3,4)))

inside: [[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]] [[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
array: [[0. 1. 2. 3.]
 [0. 2. 4. 6.]
 [0. 3. 6. 9.]]


In [39]:
print(np.random.rand(3,2))
print(np.random.randint(3, 6, size=(3,2)))

[[0.38443793 0.98356283]
 [0.62889514 0.37534796]
 [0.89242963 0.8948429 ]]
[[5 5]
 [5 3]
 [4 4]]


# Numpy 4-1

In [67]:
#numpy
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3] #View; shallow copy
print(b)
print(a[0,1])
b[0,0]=77
print(a[0,1])
print(a)

[[2 3]
 [6 7]]
2
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [91]:
#python
a = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
b = [v[1:3] for v in a[:2]] # deep copy
print(b)
print(a[0][1])
b[0][0] = 77
print(a[0][1])
print(a)

[[2, 3], [6, 7]]
2
2
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [93]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

r1 = a[1,:]
r2 = a[1:2,:]
print(r1, r1.shape, r2, r2.shape)

c1 = a[:, 1]
c2 = a[:, 1:2]
print(c1, c1.shape)
print(c2, c2.shape)

[5 6 7 8] (4,) [[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [96]:
#shallow copy
a = np.arange(10)
b = a[::2]
print(b)
print(np.may_share_memory(a,b))
b[0]=-7
print(a)

[0 2 4 6 8]
True
[-7  1  2  3  4  5  6  7  8  9]


In [99]:
#deep copy
a = np.arange(10)
c = a[::2].copy()
c[0] = 12
print(c)
print(np.may_share_memory(a,c))

[12  2  4  6  8]
False


In [103]:
a = np.array([[1,2],[3,4],[5,6]])
boll_inx = (a>2)
print(boll_inx)

print(a[boll_inx])
print(a[a>2])

a[a>2] = 0
print(a)

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[[1 2]
 [0 0]
 [0 0]]


In [105]:
a = np.arange(0, 100, 10)
print(a[[2,3,2,4,2]])
a[[9,7]] = -100
print(a)

[20 30 20 40 20]
[   0   10   20   30   40   50   60 -100   80 -100]


In [108]:
a = np.arange(10)*10
print(a)
idx = np.array([[3,4],[9,7]])
print(a[idx])

[ 0 10 20 30 40 50 60 70 80 90]
[[30 40]
 [90 70]]
