In [1]:
import numpy as np

In [4]:
a = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis] # = column matrix
mask = np.array([1, 0, 1, 0, 0, 1], dtype=bool)
print(a)
print(mask)

print(a[(0,1,2,3,4),(1,2,3,4,5)]) # row & column
print(a[3:, [0,2,5]]) 
print(a[mask,2])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[ True False  True False False  True]
[ 1 12 23 34 45]
[[30 32 35]
 [40 42 45]
 [50 52 55]]
[ 2 22 52]


In [8]:
# Casting
x = np.array([1,2,3,4], dtype = np.float)
y = x.astype(np.int8)
print(y+1, (y+1).dtype)
print(y+256, (y+256).dtype)
print(y+256.0, (y+256.0).dtype)
print(y+np.array([256], dtype=np.int32), (y+np.array([256], dtype=np.int32)).dtype)

[2 3 4 5] int8
[257 258 259 260] int16
[257. 258. 259. 260.] float64
[257 258 259 260] int32


In [10]:
print(np.float(2)) # ok
print(np.int(1.99999)) # not ok

2.0
1


# Numpy 5 (array operation / broadcasting)

In [14]:
# elementwise
a = np.array([1,2,3,4])
print(a+1)
print(a**2)
print(2**a)

c = np.ones((3,3))
print(c*c)
print(c.dot(c)) # matrix multiplication

[2 3 4 5]
[ 1  4  9 16]
[ 2  4  8 16]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [16]:
a = np.array([[1,2,3,4]])
b = a.T # shallow copy
print(b)
b[0,0] = 5
print(a)

[[1]
 [2]
 [3]
 [4]]
[[5 2 3 4]]


In [17]:
#comparison/logical operation elementwise
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [21]:
# reduction
x = np.array([1,2,3,4])
np.sum(x)

10

In [19]:
x = np.array([[1,2],[3,4]])
print(x.sum(), x.sum(axis=0), x.sum(axis=1)) # 0:column 1:row

10 [4 6] [3 7]


In [23]:
x = np.array([[1,2,3], [4,5,6]])
np.cumsum(x)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [26]:
print(np.cumsum(x, axis=0))
print(np.cumsum(x, axis=1))

[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


In [27]:
x = np.array([3,1,2])
print(x.min(), x.max(), x.argmin(), x.argmax())

1 3 1 0


In [28]:
a = np.tile(np.arange(0, 40, 10), (3,1)).T
print(a)
b = np.array([0, 1, 2])
a+b

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [29]:
a = np.arange(0, 40, 10)
a = a[:, np.newaxis]
print(a)
a+b

[[ 0]
 [10]
 [20]
 [30]]


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [30]:
a = np.arange(5)
b = np.arange(5)[:, np.newaxis]
r = np.sqrt(a**2+b**2)
r

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])

# Numpy 6 (array shape manipulation, sorting)

In [38]:
a = np.array([[1,2,3],[4,5,6]])
b = a.ravel()
c = a.flatten()
b[0] = 9 # shallow
c[1] = 8 # deep
print(a, b, c)
a.T.ravel()

[[9 2 3]
 [4 5 6]] [9 2 3 4 5 6] [1 8 3 4 5 6]


array([9, 4, 2, 5, 3, 6])

In [45]:
a = np.array([[1,2,3],[4,5,6]])
b = a.ravel()
b = b.reshape((2,3))
print(b)
b[0,0] = 9
print(a)
print(np.may_share_memory(a,b))

[[1 2 3]
 [4 5 6]]
[[9 2 3]
 [4 5 6]]
True


In [46]:
a = np.zeros((3,2))
b = a.T.reshape(3*2) # transpose disconnects link,,, reshape caution.
b[0] = 9
print(a)
print(b)
print(np.may_share_memory(a,b))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[9. 0. 0. 0. 0. 0.]
False


In [47]:
# add dimension
z = np.array([1,2,3])
print(z[:, np.newaxis])
print(z[np.newaxis, :])

[[1]
 [2]
 [3]]
[[1 2 3]]


In [50]:
# resizing
a = np.arange(4)
a.resize((8,))
b = a
print(a, b, np.may_share_memory(a,b))
a.resize((4,)) # memory ERROR

[0 1 2 3 0 0 0 0] [0 1 2 3 0 0 0 0] True


ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [54]:
# Sorting
a = np.array([[4,3,5],[1,2,1]])
b = np.sort(a, axis=1)
print(b)
a.sort(axis=0)
print(a, np.may_share_memory(a, b))

a = np.array([4,3,1,2])
j = np.argsort(a)
print(j, a[j])

[[3 4 5]
 [1 1 2]]
[[1 2 1]
 [4 3 5]] False
[2 3 1 0] [1 2 3 4]


# Numpy 7: exercise

In [65]:
# Reverse vector
a = np.arange(50)
b = np.argsort(a)
print(a[len(a)-1-b])
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [59]:
# 3*3 matrix
a = np.arange(9)
a.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
# checkerboard pattern
a = np.fromfunction(lambda i, j: (i+j)%2, (8,8), dtype=np.int)
print(a)

A = np.zeros((8,8), dtype=np.int)
A[::2, 1::2]=1
A[1::2,::2]=1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [71]:
# Normalize 5*5 random matrix
a = np.random.random((5,5))
a = (a-np.min(a))/(np.max(a)-np.min(a))
print(a)

[[0.91898058 0.97245403 0.49189397 0.69240082 0.14632686]
 [0.5162566  0.97201617 0.92702251 0.         0.12593221]
 [0.61817754 0.83753495 0.96854324 1.         0.81132281]
 [0.64931758 0.78029782 0.04534575 0.71612432 0.42253988]
 [0.92660396 0.44669716 0.40093381 0.85822737 0.28308268]]


In [75]:
#negate element
a = np.arange(11)
a[(a>3)&(a<=8)] = -a[(a>3)&(a<=8)]
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
